### ISSUE TITLE
Executable not starting on windows 10

### ISSUE THREAD

**Issue by NebXTeaath** [jstrieb/bruteforce-link-lock#1]
After "go build -o crack" command, GO creates a file named "crack" but it's not starting as an executable nor does it have .exe extension.
Any help would be appreciated.

**Comment by jstrieb** [comment]
Perhaps try the following:

```
go build -o crack.exe
```

On Windows, I believe files must have the `.exe` extension in order to run correctly. As such, I expect that if you rename the `crack` file to `crack.exe`, that will also work to be able to run it.

**Comment by NebXTeaath** [comment]
> Perhaps try the following:
> 
> ```
> go build -o crack.exe
> ```
> 
> On Windows, I believe files must have the `.exe` extension in order to run correctly. As such, I expect that if you rename the `crack` file to `crack.exe`, that will also work to be able to run it.

I'm grateful for your swift response. I attempted substituting "crack" with crack.exe, resulting in the creation of a .exe file. However, running it, even as an administrator, yields no visible outcome.

**Comment by jstrieb** [comment]
Are you running it by double clicking? It is meant to be run from the command line with some arguments. Or when you run from the command line it still does nothing?

**Comment by NebXTeaath** [comment]
> Are you running it by double clicking? It is meant to be run from the command line with some arguments. Or when you run from the command line it still does nothing? 

I used the command "start crack.exe" and also even double-clicked the .exe file in the directory for confirmation. Could you kindly advise if there are additional arguments required? I apologize for my limited familiarity with command-line operations.

**Comment by jstrieb** [comment]
I think if you just do `crack.exe` it will work, without `start`. Double clicking will almost certainly not work.

**Comment by NebXTeaath** [comment]
> I think if you just do `crack.exe` it will work, without `start`. Double clicking will almost certainly not work.

That worked, thanks, you made my day!

**Comment by jstrieb** [comment]
Glad I could help! Thanks for checking out the project! 

I may update the instructions to be clearer for Windows users thanks to your feedback.
